- block:
    - name: Enable HAProxy Service
      systemd:
        name: haproxy.service
        state: "{{ haproxy.state }}"
        enabled: "{{ haproxy.enabled }}"
  tags:
    - haproxy::systemd_unit
