- block:
    - name: Upload dnsmasq.conf
      template:
        src: etc/dnsmasq.conf.j2
        dest: /etc/dnsmasq.conf
        backup: yes
      register: dnsmasq_base
    - name: Reload Dnsmasq Base Config
      systemd:
        name: dnsmasq.service
        state: restarted
      when: dnsmasq_base.changed
    - name: Upload Static Leases Table
      template:
        src: etc/dnsmasq.d/okd-leases.conf.j2
        dest: /etc/dnsmasq.d/okd-leases.conf
        backup: yes
      register: dnsmasq_leases
    - name: Create tftp root directory
      file:
        path: "{{ item  }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      loop:
        - "{{ dnsmasq.tftp_root }}"
        - "{{ dnsmasq.tftp_root }}/pxelinux.cfg"
    - name: Copy PXELINUX boot payload
      command: >
        cp /usr/share/syslinux/pxelinux.0 /usr/share/syslinux/ldlinux.c32 {{ dnsmasq.tftp_root }}/
    - name: Fix SELinux contexts
      community.general.sefcontext:
        target: "{{ item.path }}"
        setype: "{{ item.context }}"
        state: present
      loop:
        - { path: "{{ dnsmasq.tftp_root }}(/.*)?", context: "dnsmasq_var_run_t" }
        - { path: "{{ dnsmasq.log_facility }}", context: "dnsmasq_var_log_t" }
    - name: Reload SELinux policies
      command: >
        restorecon -irv {{ item }}
      loop:
        - "{{ dnsmasq.tftp_root }}"
        - "{{ dnsmasq.log_facility }}"
    - name: Reload Dnsmasq Static Leases
      systemd:
        name: dnsmasq.service
        state: restarted
      when: dnsmasq_leases.changed
  tags:
    - dhcp::service_configuration
