- block:
    - name: Create Zone Databases Paths
      file:
        path: /etc/named/zones
        state: directory
        mode: 0755
    - name: Compile Forward Zone Database
      template:
        src: etc/named/zones/zonedb.forward.j2
        dest: /etc/named/zones/zonedb.{{ okd.base_domain }}
        backup: yes
      register: forward_zone
    - name: Compile Reverse Zone Database
      template:
        src: etc/named/zones/zonedb.reverse.j2
        dest: /etc/named/zones/zonedb.{{ okd.machine_cidr | reverse_zone }}
        backup: yes
      register: reverse_zone
    - name: Reload Forward Zone
      systemd:
        name: named.service
        state: reloaded
      when: forward_zone.changed
    - name: Reload Reverse Zone
      systemd:
        name: named.service
        state: reloaded
      when: reverse_zone.changed
  tags:
    - named::zone_config
    - named::zonefile_rendering
