- block:
    - name: Configure BIND Service
      template:
        src: etc/named.conf.j2
        dest: /etc/named.conf
        backup: yes
  tags:
    - named::named_config
    - named::dns_service
