- block:
    - name: Enable FirewallD System Service
      systemd:
        name: firewalld.service
        state: "{{ firewall.state }}"
        enabled: "{{ firewall.enabled }}"
    - name: Allow required services in FirewallD
      ansible.posix.firewalld:
        service: "ssh"
        permanent: "true"
        state: "enabled"
      register: firewall_status
    - name: Reload FirewallD Configuration
      systemd:
        name: firewalld.service
        state: restarted
      when: firewall_status.changed
  tags:
    - firewalld::network_services
    - firewalld::allowed_protocols
    - firewalld::systemd_unit
